### ISSUE TITLE
Xlib error on 15.04

### ISSUE THREAD

**Issue by iddl** [ssokolow/quicktile#52]
The `--daemonize` option triggers a python xlib error.
Currently on xubuntu 15.04

xlib version: 0.14

```
Traceback (most recent call last):
  File "./quicktile.py", line 1261, in <module>
    if not app.run():
  File "./quicktile.py", line 913, in run
    self.keybinder = KeyBinder()
  File "./quicktile.py", line 752, in __init__
    self.xdisp = xdisplay or Display()
  File "/usr/local/lib/python2.7/dist-packages/Xlib/display.py", line 85, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/local/lib/python2.7/dist-packages/Xlib/display.py", line 67, in __init__
    apply(protocol.display.Display.__init__, (self, ) + args, keys)
  File "/usr/local/lib/python2.7/dist-packages/Xlib/protocol/display.py", line 123, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0.0": Invalid MIT-MAGIC-COOKIE-1 key
```

Not sure whether this is related to quicktile itself. Has anybody had the same issue ?

**Comment by ssokolow** [comment]
Wow. That takes me back. I don't think I've seen that error in nearly 10 years.

It's not quicktile-specific and, assuming it's not some kind of weird bug affecting everything based on `python-xlib`, it means that an incorrect authentication token is stored in `~/.Xauthority`.

The solution back in the day was to `rm ~/.Xauthority*` and, if necessary, restart the X server.

**Comment by iddl** [comment]
That did it. Thanks a ton :+1:
