### ISSUE TITLE
Issue encoding UTF-8 ?

### ISSUE THREAD

**Issue by cyberviking** [ssokolow/quicktile#58]
I'm having an issue with it, ubuntu 15.04 : 

./quicktile.py --daemon
Traceback (most recent call last):
  File "/home/me/quicktile.py", line 1267, in <module>
    if not app.run():
  File "/home/me/quicktile.py", line 919, in run
    self.keybinder = KeyBinder()
  File "/home/me/quicktile.py", line 752, in __init__
    self.xdisp = xdisplay or Display()
  File "/usr/lib/python2.7/dist-packages/Xlib/display.py", line 80, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/lib/python2.7/dist-packages/Xlib/display.py", line 62, in __init__
    display.Display.__init__(*(self, ) + args, **keys)
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/display.py", line 61, in __init__
    name, host, displayno)
  File "/usr/lib/python2.7/dist-packages/Xlib/support/connect.py", line 93, in get_auth
    return getattr(mod, modname).get_auth(sock, dname, host, dno)
  File "/usr/lib/python2.7/dist-packages/Xlib/support/unix_connect.py", line 116, in new_get_auth
    au = xauth.Xauthority()
  File "/usr/lib/python2.7/dist-packages/Xlib/xauth.py", line 84, in __init__
    self.entries.append((family, addr.decode('UTF-8'),
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc0 in position 0: invalid start byte

**Comment by ssokolow** [comment]
That's not a QuickTile issue, but I'll see what I can do to help.

The problem is that, when QuickTile asks `python-xlib` to open a connection to your X server, `python-xlib` blows up trying to parse your `.Xauthority` file. (Found at either `$XAUTHORITY` or `~/.Xauthority`)

Given the line it's dying on, my first question would be to ask whether your hostname (or `DISPLAY`, if you're remoting) contains non-ASCII characters which might have been encoded in something other than UTF-8.

Failing that, I'd suggest deleting your Xauthority file and then restarting your X server to force the regeneration of a clean one.

**Comment by cyberviking** [comment]
Oh sorry, i'm not very familiar with `python` and/or `xlib`.
And you already solved my problem, I'm happy to use QuickTile again.
Congratulation for you work, I love it !
